name: Auto Update IPTV List

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update IPTV list
        run: |
          echo "Updating IPTV list..."
          # Ovdje možeš dodati skriptu za automatsko osvježavanje linkova
          # Za sada samo potvrđujemo da fajl postoji
          ls -la

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update IPTV list" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
